# Generated by Skyramp v1.3.14 on 2026-03-20 17:47:51.536165018 +0000 UTC m=+223.351157274
# Command: skyramp generate contract rest http://localhost:4200/api/flows \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_flows_version_field_provider.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"test-flow-contract-1742400000","tags":[],"labels":{}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "labels": {},
        "name": "test-flow-contract-1742400000",
        "tags": []
    }'''

    # Expected Response Body
    expected_flows_POST_response_body = r'''{
        "created": "string",
        "id": "b8d079bc-4613-48a5-ac24-c295f234465f",
        "labels": "",
        "name": "my-flow",
        "tags": [
            "string"
        ],
        "updated": "string",
        "version": 1
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flows_POST_response.status_code == 200
    assert skyramp.check_schema(flows_POST_response, expected_flows_POST_response_body)
    assert skyramp.get_response_value(flows_POST_response, "created") is not None
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    assert skyramp.get_response_value(flows_POST_response, "labels") is not None


if __name__ == "__main__":
    test_flows_post()
