# Generated by Skyramp v1.3.16 on 2026-04-13 19:35:42.230651608 +0000 UTC m=+531.798969593
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id} \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_flow_by_id_provider.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--parent-request-data id={"name": "test-flow-get-by-id-1742400000", "tags": [], "labels": {}} \
# 		--parent-status-code id=200 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id} GET
def test_flows_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "65fb037e-6182-4056-bee0-f28acdf60291"

    # Expected Response Body
    expected_flows_id_GET_response_body = r'''{
        "created": "string",
        "id": "3bbb18ae-8c42-4de0-8402-7bf0e4f52430",
        "labels": "",
        "name": "my-flow",
        "tags": [
            "string"
        ],
        "updated": "string",
        "version": 1
    }'''

    # Execute Request
    flows_id_GET_response = client.send_request(
        url=URL,
        path="/api/flows/{id}",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert flows_id_GET_response.status_code == 200
    assert skyramp.check_schema(flows_id_GET_response, expected_flows_id_GET_response_body)
    assert skyramp.get_response_value(flows_id_GET_response, "created") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "id") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "labels") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "name") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "version") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "version") >= 1


if __name__ == "__main__":
    test_flows_id_get()
