# Generated by Skyramp v1.3.14 on 2026-03-20 18:33:08.27860633 +0000 UTC m=+348.180013856
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_run_state_history_workflow_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-run-state-history-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-state-history-flow"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{{"flow_id": "{}", "name": "test-state-history-run"}}'.format(skyramp.get_response_value(endpoint_2_POST_response, "id"))
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    states_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/states",
        method="GET",
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert states_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
