# Generated by Skyramp v1.3.14 on 2026-03-20 17:48:03.951840938 +0000 UTC m=+235.766833234
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_task_run_mapped_fields_defaults.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_task-run-mapped-fields-defaults.json

# Import of required libraries
import skyramp
import json
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "labels": {},
        "name": "test-flow-mapped-task-1742400000",
        "tags": []
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201

    # Request Body
    flow_runs_POST_request_body = json.dumps({
        "flow_id": skyramp.get_response_value(flows_POST_response, "id"),
        "name": "test-flow-run-mapped-1742400000",
        "tags": []
    })
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs",
        method="POST",
        body=flow_runs_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201

    # Request Body
    task_runs_POST_request_body = json.dumps({
        "dynamic_key": "test-task-0",
        "flow_run_id": skyramp.get_response_value(flow_runs_POST_response, "id"),
        "name": "test-task-run-mapped-1742400000",
        "tags": [],
        "task_key": "test-task"
    })
    
    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert task_runs_POST_response.status_code == 201

    # Execute Request
    task_runs_task_runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/{task_runs}",
        method="GET",
        headers=headers,
        path_params={"task_runs": skyramp.get_response_value(task_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert task_runs_task_runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
