# Generated by Skyramp v1.3.14 on 2026-03-20 18:33:10.127070109 +0000 UTC m=+350.028477639
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_run_states_not_found_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-run-states-not-found.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    states_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/3fa85f64-5717-4562-b3fc-2c963f66afa6/states",
        method="GET"
    )
    # Generated Assertions
    assert states_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
