# Generated by Skyramp v1.3.14 on 2026-03-20 17:47:58.242515123 +0000 UTC m=+230.057507509
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_version_initial_value.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-version-initial-value.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "labels": {},
        "name": "test-flow-version-init-1742400000",
        "tags": []
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201

    # Execute Request
    flows_flows_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(flows_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_flows_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
