# Generated by Skyramp v1.3.14 on 2026-03-20 18:24:15.034658576 +0000 UTC m=+207.867226383
# Command: skyramp generate contract rest http://localhost:4200/api/deployments/{id}/schedules/preview \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--path-params id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/deployments/{id}/schedules/preview GET
def test_preview_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_preview_GET_response_body = r'''"string"'''

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL,
        path="/api/deployments/{id}/schedules/preview",
        method="GET",
        headers=headers,
        path_params={"id": id},
        query_params={
            "format": "list",
            "n": 5
        }
    )

    # Generated Assertions
    assert preview_GET_response.status_code == 200
    assert skyramp.check_schema(preview_GET_response, expected_preview_GET_response_body)


if __name__ == "__main__":
    test_preview_get()
