# Generated by Skyramp v1.3.14 on 2026-03-20 18:20:49.310733732 +0000 UTC m=+273.544582111
# Command: skyramp generate contract rest http://localhost:4200/api/task_runs/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"task_key":"business_rule_task-1234567890","dynamic_key":"0","name":"business-rule-task-run","tags":[],"labels":{},"task_inputs":{},"empirical_policy":{}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task_runs/ POST
def test_task_runs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    task_runs_POST_request_body = r'''{
        "dynamic_key": "0",
        "empirical_policy": {},
        "labels": {},
        "name": "business-rule-task-run",
        "tags": [],
        "task_inputs": {},
        "task_key": "business_rule_task-1234567890"
    }'''

    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL,
        path="/api/task_runs/",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(task_runs_POST_response, "20x")


if __name__ == "__main__":
    test_task_runs_post()
