# Generated by Skyramp v1.3.14 on 2026-03-20 18:32:09.061780594 +0000 UTC m=+288.963188119
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/states \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--parent-request-data {"id":"{\"flow_id\": \"3fa85f64-5717-4562-b3fc-2c963f66afb6\", \"name\": \"contract-test-run\"}"} \
# 		--parent-status-code {"id":"201"} \
# 		--path-params id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/states GET
def test_states_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_states_GET_response_body = r'''[
        {
            "data": "string",
            "id": "7c0ac0b9-23f2-4b76-8989-1f657aeeaa8d",
            "message": "Run started",
            "name": "string",
            "state_details": {
                "cache_expiration": "string",
                "cache_key": "string",
                "child_flow_run_id": "string",
                "deferred": "false",
                "deployment_concurrency_lease_id": "string",
                "flow_run_id": "string",
                "pause_key": "string",
                "pause_reschedule": false,
                "pause_timeout": "string",
                "refresh_cache": "string",
                "retriable": "string",
                "run_input_keyset": "string",
                "scheduled_time": "string",
                "task_parameters_id": "string",
                "task_run_id": "string",
                "traceparent": "string",
                "transition_id": "string",
                "untrackable_result": false
            },
            "timestamp": "2026-03-20T18:32:09Z",
            "type": "SCHEDULED"
        }
    ]'''

    # Execute Request
    states_GET_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/states",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert states_GET_response.status_code == 200
    assert skyramp.check_schema(states_GET_response, expected_states_GET_response_body)
    assert skyramp.get_response_value(states_GET_response, "0.data") is not None
    assert skyramp.get_response_value(states_GET_response, "0.id") is not None
    assert skyramp.get_response_value(states_GET_response, "0.message") is not None


if __name__ == "__main__":
    test_states_get()
