# Generated by Skyramp v1.3.14 on 2026-03-20 18:26:04.303673953 +0000 UTC m=+78.866499088
# Command: skyramp generate fuzz rest http://localhost:4200/api/work_queues/{id}/stats \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--path-params id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/work_queues/{id}/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}/stats",
        method="GET",
        headers=headers,
        path_params={"id": id},
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_stats_get()
