# Generated by Skyramp v1.3.14 on 2026-03-20 18:26:14.607112428 +0000 UTC m=+89.169937544
# Command: skyramp generate contract rest http://localhost:4200/api/work_queues/{id}/stats \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--parent-request-data {"id":"{\"name\": \"test-contract-queue\", \"description\": \"Queue for contract testing\"}"} \
# 		--parent-status-code {"id":"201"} \
# 		--path-params id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/work_queues/{id}/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_stats_GET_response_body = r'''{
        "available_slots": "string",
        "concurrency_limit": "string",
        "running_runs": 0,
        "scheduled_runs": 0,
        "work_queue_id": "42084eec-6811-4fc0-9b75-5603715ffbcc"
    }'''

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}/stats",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.check_schema(stats_GET_response, expected_stats_GET_response_body)
    assert skyramp.get_response_value(stats_GET_response, "available_slots") is not None
    assert skyramp.get_response_value(stats_GET_response, "concurrency_limit") is not None
    assert skyramp.get_response_value(stats_GET_response, "running_runs") is not None


if __name__ == "__main__":
    test_stats_get()
