# Generated by Skyramp v1.3.14 on 2026-03-20 18:21:05.279191007 +0000 UTC m=+289.513039356
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output task_run_filter_workflow_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_task-run-filter-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "dynamic_key": "0",
        "empirical_policy": {},
        "labels": {},
        "name": "filter-workflow-run",
        "tags": [],
        "task_inputs": {},
        "task_key": "filter_workflow_task-9876543210"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    filter_POST_request_body = r'''{
        "limit": 10,
        "offset": 0
    }'''
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
