# Generated by Skyramp v1.3.14 on 2026-03-20 18:20:47.533857054 +0000 UTC m=+271.767705423
# Command: skyramp generate contract rest http://localhost:4200/api/task_runs/{id} \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--path-params id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task_runs/{id} GET
def test_task_runs_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    task_runs_id_GET_response = client.send_request(
        url=URL,
        path="/api/task_runs/{id}",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(task_runs_id_GET_response, "20x")


if __name__ == "__main__":
    test_task_runs_id_get()
