# Generated by Skyramp v1.3.14 on 2026-03-20 18:20:59.487775008 +0000 UTC m=+283.721623367
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output task_run_mapped_fields_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_task-run-mapped-fields.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "dynamic_key": "0",
        "empirical_policy": {},
        "labels": {},
        "name": "mapped-task-run",
        "tags": [],
        "task_inputs": {},
        "task_key": "my_mapped_task-1234567890"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    task_runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/{task_runs}",
        method="GET",
        path_params={"task_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert task_runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
