# Generated by Skyramp v1.3.13 on 2026-03-16 20:39:28.561724199 +0000 UTC m=+186.325123703
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_state_history_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-run-state-history.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "state-history-test-flow"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{\"flow_id\": \"' + skyramp.get_response_value(endpoint_2_POST_response, "id") + '\"}'
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    set_state_POST_request_body = r'''{
        "state": {
            "message": "Flow run is now running",
            "name": "Running",
            "type": "RUNNING"
        }
    }'''
    
    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 201

    # Execute Request
    states_GET_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/states",
        method="GET",
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert states_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
