# Generated by Skyramp v1.3.12 on 2026-03-12 21:00:24.83962422 +0000 UTC m=+198.787766684
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_create_with_version.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-create-with-version.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    name = "flow-version-explicit-test"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {},
        "name": "flow-version-explicit-test",
        "tags": [
            "version-tracking"
        ],
        "version": 5
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        data_override={"name": name}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    name_GET_response = client.send_request(
        url=URL_,
        path="/api/flows/name/{name}",
        method="GET",
        path_params={"name": name}
    )
    # Generated Assertions
    assert name_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
