# Generated by Skyramp v1.3.13 on 2026-03-16 21:33:57.091256509 +0000 UTC m=+214.830536935
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_mapped_task_run_fields_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_mapped-task-run-fields.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "name": "mapped-task-test-flow",
        "tags": []
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201

    # Request Body
    flow_runs_POST_request_body = r'''{
        "context": {},
        "flow_id": "''' + skyramp.get_response_value(flows_POST_response, "id") + r'''",
        "name": "mapped-task-test-flow-run",
        "parameters": {},
        "tags": []
    }'''
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/",
        method="POST",
        body=flow_runs_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201

    # Request Body
    task_runs_POST_request_body = r'''{
        "dynamic_key": "0",
        "flow_run_id": "''' + skyramp.get_response_value(flow_runs_POST_response, "id") + r'''",
        "name": "mapped-task-run-0",
        "tags": [],
        "task_key": "test-mapped-task"
    }'''
    
    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/task_runs/",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert task_runs_POST_response.status_code == 201

    # Execute Request
    task_runs_task_runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/task_runs/{task_runs}",
        method="GET",
        headers=headers,
        path_params={"task_runs": skyramp.get_response_value(task_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert task_runs_task_runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
