# Generated by Skyramp v1.3.12 on 2026-03-12 19:15:36.285772739 +0000 UTC m=+153.967794274
# Command: skyramp generate contract rest http://localhost:4200/api/flows/00000000-0000-0000-0000-000000000001 \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_get_by_id_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/00000000-0000-0000-0000-000000000001 GET
def test_endpoint_00000000_0000_0000_0000_000000000001_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_00000000_0000_0000_0000_000000000001_GET_response = client.send_request(
        url=URL,
        path="/api/flows/00000000-0000-0000-0000-000000000001",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_00000000_0000_0000_0000_000000000001_GET_response, "20x")


if __name__ == "__main__":
    test_endpoint_00000000_0000_0000_0000_000000000001_get()
