# Generated by Skyramp v1.3.14 on 2026-03-20 18:25:39.929200867 +0000 UTC m=+292.761768654
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_deployment_schedule_preview_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_deployment-schedule-preview-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "name": "workflow-preview-flow-20260320",
        "tags": []
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201

    # Request Body
    deployments_POST_request_body = '{{"flow_id": "{}", "name": "workflow-preview-deploy-20260320", "paused": false, "schedules": [], "tags": []}}'.format(
        skyramp.get_response_value(flows_POST_response, "id")
    )
    
    # Execute Request
    deployments_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments",
        method="POST",
        body=deployments_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert deployments_POST_response.status_code == 201

    # Request Body
    schedules_POST_request_body = r'''[
        {
            "active": true,
            "schedule": {
                "cron": "0 * * * *",
                "timezone": "UTC",
                "type": "CronSchedule"
            }
        }
    ]'''
    
    # Execute Request
    schedules_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/{deployments}/schedules",
        method="POST",
        body=schedules_POST_request_body,
        headers=headers,
        path_params={"deployments": skyramp.get_response_value(deployments_POST_response, "id")}
    )
    # Generated Assertions
    assert schedules_POST_response.status_code == 201

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/{deployments}/schedules/preview",
        method="GET",
        headers=headers,
        path_params={"deployments": skyramp.get_response_value(deployments_POST_response, "id")},
        query_params={
            "format": ["list"],
            "n": ["3"]
        }
    )
    # Generated Assertions
    assert preview_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
