# Generated by Skyramp v1.3.13 on 2026-03-16 19:54:27.004214107 +0000 UTC m=+115.988840124
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/states \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_run_states_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--path-params id=00000000-0000-0000-0000-000000000000 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/states GET
def test_states_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "00000000-0000-0000-0000-000000000000"

    # Expected Response Body
    expected_states_GET_response_body = r'''[
        {
            "data": "string",
            "id": "39f5c9a1-697c-4670-b6c1-8d8b5b4b844f",
            "message": "Run started",
            "name": "string",
            "state_details": {
                "cache_expiration": "string",
                "cache_key": "string",
                "child_flow_run_id": "string",
                "deferred": "false",
                "deployment_concurrency_lease_id": "string",
                "flow_run_id": "string",
                "pause_key": "string",
                "pause_reschedule": false,
                "pause_timeout": "string",
                "refresh_cache": "string",
                "retriable": "string",
                "run_input_keyset": "string",
                "scheduled_time": "string",
                "task_parameters_id": "string",
                "task_run_id": "string",
                "traceparent": "string",
                "transition_id": "string",
                "untrackable_result": false
            },
            "timestamp": "2026-03-16T19:54:27Z",
            "type": "SCHEDULED"
        }
    ]'''

    # Execute Request
    states_GET_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/states",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert states_GET_response.status_code == 200
    assert skyramp.check_schema(states_GET_response, expected_states_GET_response_body)
    assert skyramp.get_response_value(states_GET_response, "0.data") is not None
    assert skyramp.get_response_value(states_GET_response, "0.id") is not None
    assert skyramp.get_response_value(states_GET_response, "0.message") is not None


if __name__ == "__main__":
    test_states_get()
