# Generated by Skyramp v1.3.14 on 2026-03-20 18:25:12.178121132 +0000 UTC m=+265.010688919
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_schedules_preview_not_found.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_schedules-preview-not-found.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/3fa85f64-5717-4562-b3fc-2c963f66afa6/schedules/preview",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert preview_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
