# Generated by Skyramp v1.3.13 on 2026-03-17 02:46:56.445126977 +0000 UTC m=+159.814645895
# Command: skyramp generate contract rest http://localhost:4200/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_deployment_schedule_preview_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--query-params format=detailed,n=5 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview GET
def test_preview_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_preview_GET_response_body = r'''"string"'''

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL,
        path="/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview",
        method="GET",
        headers=headers,
        query_params={
            "format": "detailed",
            "n": "5"
        }
    )

    # Generated Assertions
    assert preview_GET_response.status_code == 200
    assert skyramp.check_schema(preview_GET_response, expected_preview_GET_response_body)


if __name__ == "__main__":
    test_preview_get()
