# Generated by Skyramp v1.3.12 on 2026-03-12 19:16:00.761973187 +0000 UTC m=+178.443994723
# Command: skyramp generate contract rest http://localhost:4200/api/flows/name/version-test-flow-20260312 \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_get_by_name_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/name/version-test-flow-20260312 GET
def test_version_test_flow_20260312_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    version_test_flow_20260312_GET_response = client.send_request(
        url=URL,
        path="/api/flows/name/version-test-flow-20260312",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(version_test_flow_20260312_GET_response, "20x")


if __name__ == "__main__":
    test_version_test_flow_20260312_get()
