# Generated by Skyramp v1.3.13 on 2026-03-16 21:34:56.363243125 +0000 UTC m=+274.102523591
# Command: skyramp generate contract rest http://localhost:4200/api/task_runs \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_task_run_mapped_fields_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"task_key":"contract-test-task","dynamic_key":"contract-0","name":"contract-task-run","tags":[]} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task_runs POST
def test_task_runs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    task_runs_POST_request_body = r'''{
        "dynamic_key": "contract-0",
        "name": "contract-task-run",
        "tags": [],
        "task_key": "contract-test-task"
    }'''

    # Expected Response Body
    expected_task_runs_POST_response_body = r'''{
        "cache_expiration": "string",
        "cache_key": "string",
        "created": "string",
        "dynamic_key": "string",
        "empirical_policy": {
            "max_retries": 0,
            "retries": "string",
            "retry_delay": "string",
            "retry_delay_seconds": 0,
            "retry_jitter_factor": "string"
        },
        "end_time": "string",
        "estimated_run_time": 0,
        "estimated_start_time_delta": 0,
        "expected_start_time": "string",
        "flow_run_id": "string",
        "flow_run_run_count": 0,
        "id": "8fef3bc4-4154-4198-a3da-6026767a6fdb",
        "labels": "",
        "map_index": -1,
        "mapped": false,
        "name": "my-task-run",
        "next_scheduled_start_time": "string",
        "run_count": 0,
        "start_time": "string",
        "state": "string",
        "state_id": "string",
        "state_name": "string",
        "state_type": "string",
        "tags": [
            "string"
        ],
        "task_inputs": {
            "key": [
                "string"
            ]
        },
        "task_key": "string",
        "task_version": "string",
        "total_run_time": 0,
        "updated": "string"
    }'''

    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL,
        path="/task_runs/",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert task_runs_POST_response.status_code in (200, 201)
    assert skyramp.check_schema(task_runs_POST_response, expected_task_runs_POST_response_body)
    assert skyramp.get_response_value(task_runs_POST_response, "cache_expiration") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "cache_key") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "created") is not None


if __name__ == "__main__":
    test_task_runs_post()
