# Generated by Skyramp v1.3.13 on 2026-03-16 20:59:25.27933158 +0000 UTC m=+148.696199694
# Command: skyramp generate contract rest http://localhost:4200/api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_work_queue_stats_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_stats_GET_response_body = r'''{
        "available_slots": "string",
        "concurrency_limit": "string",
        "running_runs": 0,
        "scheduled_runs": 0,
        "work_queue_id": "b1692163-db9d-416a-89d2-c22f70c8e27e"
    }'''

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.check_schema(stats_GET_response, expected_stats_GET_response_body)
    assert skyramp.get_response_value(stats_GET_response, "available_slots") is not None
    assert skyramp.get_response_value(stats_GET_response, "concurrency_limit") is not None
    assert skyramp.get_response_value(stats_GET_response, "running_runs") is not None


if __name__ == "__main__":
    test_stats_get()
