# Generated by Skyramp v1.3.12 on 2026-03-12 17:18:42.453995864 +0000 UTC m=+149.273657417
# Command: skyramp generate fuzz rest http://localhost:4200/api/flows/00000000-0000-0000-0000-000000000001 \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_flow_update_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"tags":["fuzz-test"],"labels":{"env":"test","priority":1,"active":true}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flows/00000000-0000-0000-0000-000000000001 PATCH
def test_endpoint_00000000_0000_0000_0000_000000000001_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body = r'''{
      "tags": [
        "fuzz-test"
      ],
      "labels": {
        "env": "test",
        "priority": 1,
        "active": true
      }
    }'''
    
    # Fuzz strategies
    endpoint_00000000_0000_0000_0000_000000000001_patch_fuzzed_body = {
        "labels": {
            "active": True,
            "env": "0123456789",
            "priority": -10
        },
        "tags": ["0123456789"]
    }
    # Fuzz status codes
    expected_endpoint_00000000_0000_0000_0000_000000000001_patch_status_code = {
        "labels": {
            "active": "40x",
            "env": "40x",
            "priority": "40x"
        },
        "tags": ["40x"]
    }
    # Fuzz status codes for Null values
    expected_endpoint_00000000_0000_0000_0000_000000000001_patch_null_status_code = {
        "labels": {
            "active": "40x",
            "env": "40x",
            "priority": "40x"
        },
        "tags": ["40x"]
    }

    # Execute Request
    endpoint_00000000_0000_0000_0000_000000000001_PATCH_response = client.send_request(
        url=URL,
        path="/api/flows/00000000-0000-0000-0000-000000000001",
        method="PATCH",
        body=endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_00000000_0000_0000_0000_000000000001_patch_fuzzed_body):
        # Execute Request
        endpoint_00000000_0000_0000_0000_000000000001_PATCH_response = client.send_request(
            url=URL,
            path="/api/flows/00000000-0000-0000-0000-000000000001",
            method="PATCH",
            body=endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_00000000_0000_0000_0000_000000000001_patch_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_00000000_0000_0000_0000_000000000001_patch_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_00000000_0000_0000_0000_000000000001_patch_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_00000000_0000_0000_0000_000000000001_PATCH_response = client.send_request(
            url=URL,
            path="/api/flows/00000000-0000-0000-0000-000000000001",
            method="PATCH",
            body=endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_00000000_0000_0000_0000_000000000001_patch_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_00000000_0000_0000_0000_000000000001_patch()
