# Generated by Skyramp v1.3.12 on 2026-03-13 19:41:20.892952885 +0000 UTC m=+253.876465887
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_mapped_task_run_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_mapped-task-run-lifecycle.json

# Import of required libraries
import json
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    flows_POST_request_body = r'''{
        "name": "map-test-flow-001",
        "tags": [
            "mapping-test"
        ]
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code in (200, 201)

    # Request Body
    flow_runs_POST_request_body = json.dumps({
        "flow_id": skyramp.get_response_value(flows_POST_response, "id"),
        "name": "map-test-run-001",
        "tags": ["mapping-test"]
    })

    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=flow_runs_POST_request_body
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code in (200, 201)

    # Request Body
    task_runs_POST_request_body = json.dumps({
        "dynamic_key": "0",
        "flow_run_id": skyramp.get_response_value(flow_runs_POST_response, "id"),
        "name": "process-item-0",
        "tags": ["mapped-task"],
        "task_key": "process_item"
    })
    
    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/",
        method="POST",
        body=task_runs_POST_request_body
    )
    # Generated Assertions
    assert task_runs_POST_response.status_code in (200, 201)

    # Execute Request
    task_runs_task_runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task_runs/{task_runs}",
        method="GET",
        path_params={"task_runs": skyramp.get_response_value(task_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert task_runs_task_runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
