# Generated by Skyramp v1.3.12 on 2026-03-12 17:19:08.455470342 +0000 UTC m=+175.275131885
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_multi_version_increment.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-multi-version-increment.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {},
        "name": "multi-version-test-flow-20260312",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    flows_PATCH_request_body = r'''{
        "tags": [
            "v2"
        ]
    }'''
    
    # Execute Request
    flows_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="PATCH",
        body=flows_PATCH_request_body,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_PATCH_response.status_code == 204

    # Request Body
    flows_PATCH_1_request_body = r'''{
        "labels": {
            "tier": "gold"
        },
        "tags": [
            "v3"
        ]
    }'''
    
    # Execute Request
    flows_PATCH_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="PATCH",
        body=flows_PATCH_1_request_body,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_PATCH_1_response.status_code == 204

    # Execute Request
    flows_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="GET",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
