# Generated by Skyramp v1.3.13 on 2026-03-16 19:28:36.784626929 +0000 UTC m=+148.866762901
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_state_history.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-run-state-history.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "state-history-test-flow",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "context": {},
        "flow_id": "FLOW_ID_PLACEHOLDER",
        "name": "state-history-test-run",
        "parameters": {},
        "state": {
            "type": "PENDING"
        },
        "tags": []
    }'''
    endpoint_1_POST_request_body = endpoint_1_POST_request_body.replace("FLOW_ID_PLACEHOLDER", skyramp.get_response_value(endpoint_2_POST_response, "id"))

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "name": "Running",
            "type": "RUNNING"
        }
    }'''
    
    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 201

    # Request Body
    set_state_POST_1_request_body = r'''{
        "force": true,
        "state": {
            "name": "Completed",
            "type": "COMPLETED"
        }
    }'''
    
    # Execute Request
    set_state_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_1_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_1_response.status_code == 201

    # Execute Request
    states_GET_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/states",
        method="GET",
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert states_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
