# Generated by Skyramp v1.3.12 on 2026-03-12 19:15:36.721911018 +0000 UTC m=+154.403932553
# Command: skyramp generate fuzz rest http://localhost:4200/api/flows/filter \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_filter_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flows":{"name":{"any_":["filter-test-flow-20260312"]},"tags":{"all_":["testbot"]}},"limit":10,"offset":0} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flows/filter POST
def test_filter_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    filter_POST_request_body = r'''{
      "flows": {
        "name": {
          "any_": [
            "filter-test-flow-20260312"
          ]
        },
        "tags": {
          "all_": [
            "testbot"
          ]
        }
      },
      "limit": 10,
      "offset": 0
    }'''
    
    # Fuzz strategies
    filter_post_fuzzed_body = {
        "flows": {
            "name": {"any_": ["0123456789"]},
            "tags": {"all_": ["0123456789"]}
        },
        "limit": -10,
        "offset": -10
    }
    # Fuzz status codes
    expected_filter_post_status_code = {
        "flows": {
            "name": {"any_": ["40x"]},
            "tags": {"all_": ["40x"]}
        },
        "limit": "40x",
        "offset": "40x"
    }
    # Fuzz status codes for Null values
    expected_filter_post_null_status_code = {
        "flows": {
            "name": {"any_": ["40x"]},
            "tags": {"all_": ["40x"]}
        },
        "limit": "40x",
        "offset": "40x"
    }

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL,
        path="/api/flows/filter",
        method="POST",
        body=filter_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(filter_post_fuzzed_body):
        # Execute Request
        filter_POST_response = client.send_request(
            url=URL,
            path="/api/flows/filter",
            method="POST",
            body=filter_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(filter_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_filter_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(filter_post_fuzzed_body, key) }'
        )

        # Execute Request
        filter_POST_response = client.send_request(
            url=URL,
            path="/api/flows/filter",
            method="POST",
            body=filter_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_filter_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_filter_post()
