# Generated by Skyramp v1.3.12 on 2026-03-12 19:45:48.300841418 +0000 UTC m=+217.302499698
# Command: skyramp generate fuzz rest http://localhost:4200/api/flows/count \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_count_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flows":{"name":{"any_":["testbot-flow"]}}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flows/count POST
def test_count_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    count_POST_request_body = r'''{
      "flows": {
        "name": {
          "any_": [
            "testbot-flow"
          ]
        }
      }
    }'''
    
    # Fuzz strategies
    count_post_fuzzed_body = {"flows": {"name": {"any_": ["0123456789"]}}}
    # Fuzz status codes
    expected_count_post_status_code = {"flows": {"name": {"any_": ["40x"]}}}
    # Fuzz status codes for Null values
    expected_count_post_null_status_code = {"flows": {"name": {"any_": ["40x"]}}}

    # Execute Request
    count_POST_response = client.send_request(
        url=URL,
        path="/api/flows/count",
        method="POST",
        body=count_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(count_post_fuzzed_body):
        # Execute Request
        count_POST_response = client.send_request(
            url=URL,
            path="/api/flows/count",
            method="POST",
            body=count_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(count_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_count_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(count_post_fuzzed_body, key) }'
        )

        # Execute Request
        count_POST_response = client.send_request(
            url=URL,
            path="/api/flows/count",
            method="POST",
            body=count_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_count_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_count_post()
