# Generated by Skyramp v1.3.13 on 2026-03-17 02:47:06.456987755 +0000 UTC m=+169.826506663
# Command: skyramp generate fuzz rest http://localhost:4200/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_deployment_schedule_preview_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--query-params n=5,format=list \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview GET
def test_preview_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Fuzz strategies
    preview_get_fuzzed_query = {
        "format": "list",
        "n": "5"
    }
    # Fuzz status codes
    expected_preview_get_fuzzed_query_status_code = {
        "format": "40x",
        "n": "40x"
    }

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL,
        path="/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview",
        method="GET",
        headers=headers,
        query_params={
            "format": "list",
            "n": "5"
        },
        expected_code="20x"
    )

    for key in preview_get_fuzzed_query:
        query_params = {
            "format": "list",
            "n": "5"
        }

        query_params[key] = preview_get_fuzzed_query[key]

        # Execute Request
        preview_GET_response = client.send_request(
            url=URL,
            path="/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_preview_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { preview_get_fuzzed_query[key] }'
        )

        query_params = {
            "format": "list",
            "n": "5"
        }

        query_params[key] = ""

        # Execute Request
        preview_GET_response = client.send_request(
            url=URL,
            path="/api/deployments/22222222-2222-2222-2222-222222222222/schedules/preview",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_preview_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_preview_get()
