# Generated by Skyramp v1.3.13 on 2026-03-16 20:59:25.624233502 +0000 UTC m=+149.041101626
# Command: skyramp generate fuzz rest http://localhost:4200/api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_work_queue_stats_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/a1b2c3d4-e5f6-7890-abcd-ef1234567890/stats",
        method="GET",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_stats_get()
