# Generated by Skyramp v1.3.13 on 2026-03-16 20:59:23.140841502 +0000 UTC m=+146.557709606
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_work_queue_stats_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_work-queue-stats-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    work_queues_POST_request_body = r'''{
        "concurrency_limit": 5,
        "description": "Work queue for stats endpoint testing",
        "is_paused": false,
        "name": "stats-test-queue"
    }'''
    
    # Execute Request
    work_queues_POST_response = client.send_request(
        url=URL_localhost,
        path="/work_queues",
        method="POST",
        body=work_queues_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert work_queues_POST_response.status_code == 201

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/work_queues/{work_queues}/stats",
        method="GET",
        headers=headers,
        path_params={"work_queues": skyramp.get_response_value(work_queues_POST_response, "id")}
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
