# Generated by Skyramp v1.3.12 on 2026-03-12 21:00:24.91340811 +0000 UTC m=+198.861550594
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/flows/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_version_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"flow-contract-test","tags":["contract"],"labels":{}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "labels": {},
        "name": "flow-contract-test",
        "tags": [
            "contract"
        ]
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flows_POST_response, "20x")


if __name__ == "__main__":
    test_flows_post()
