# Generated by Skyramp v1.3.13 on 2026-03-16 20:39:52.389394118 +0000 UTC m=+210.152793622
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/a1b2c3d4-e5f6-7890-abcd-ef1234567890/states \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_run_states_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/a1b2c3d4-e5f6-7890-abcd-ef1234567890/states GET
def test_states_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_states_GET_response_body = r'''[
        {
            "data": "string",
            "id": "25e1d1af-1b91-47c3-b3d4-ba570fca26d9",
            "message": "Run started",
            "name": "string",
            "state_details": {
                "cache_expiration": "string",
                "cache_key": "string",
                "child_flow_run_id": "string",
                "deferred": "false",
                "deployment_concurrency_lease_id": "string",
                "flow_run_id": "string",
                "pause_key": "string",
                "pause_reschedule": false,
                "pause_timeout": "string",
                "refresh_cache": "string",
                "retriable": "string",
                "run_input_keyset": "string",
                "scheduled_time": "string",
                "task_parameters_id": "string",
                "task_run_id": "string",
                "traceparent": "string",
                "transition_id": "string",
                "untrackable_result": false
            },
            "timestamp": "2026-03-16T20:39:52Z",
            "type": "SCHEDULED"
        }
    ]'''

    # Execute Request
    states_GET_response = client.send_request(
        url=URL,
        path="/api/flow_runs/a1b2c3d4-e5f6-7890-abcd-ef1234567890/states",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert states_GET_response.status_code == 200
    assert skyramp.check_schema(states_GET_response, expected_states_GET_response_body)
    assert skyramp.get_response_value(states_GET_response, "0.data") is not None
    assert skyramp.get_response_value(states_GET_response, "0.id") is not None
    assert skyramp.get_response_value(states_GET_response, "0.message") is not None


if __name__ == "__main__":
    test_states_get()
