# Generated by Skyramp v1.3.13 on 2026-03-17 02:12:59.561327893 +0000 UTC m=+140.847335112
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_deployment_schedule_preview_detailed_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_deployment-schedule-preview-detailed.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-schedule-detailed",
        "tags": [
            "testing"
        ]
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "flow_id": "00000000-0000-0000-0000-000000000001",
        "labels": {},
        "name": "test-deployment-schedule-detailed",
        "paused": false,
        "schedules": [
            {
                "active": true,
                "parameters": {},
                "schedule": {
                    "cron": "0 * * * *",
                    "day_or": true,
                    "timezone": "UTC"
                }
            }
        ],
        "tags": [
            "testing"
        ]
    }'''.replace('"00000000-0000-0000-0000-000000000001"', '"' + skyramp.get_response_value(endpoint_2_POST_response, "id") + '"')
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/{deployments}/schedules/preview",
        method="GET",
        headers=headers,
        path_params={"deployments": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        query_params={"format": "detailed"}
    )
    # Generated Assertions
    assert preview_GET_response.status_code == 200
    assert skyramp.get_response_value(preview_GET_response, "deployment_id") is not None
    assert skyramp.get_response_value(preview_GET_response, "schedule_count") is not None
    assert skyramp.get_response_value(preview_GET_response, "upcoming") is not None
    assert skyramp.get_response_value(preview_GET_response, "total_requested") is not None


if __name__ == "__main__":
    test_integration()
