# Generated by Skyramp v1.3.12 on 2026-03-12 19:45:47.91072229 +0000 UTC m=+216.912380560
# Command: skyramp generate contract rest http://localhost:4200/api/flows/filter \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_filter_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flows":{"name":{"any_":["testbot-flow"]}}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/filter POST
def test_filter_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    filter_POST_request_body = r'''{
        "flows": {
            "name": {
                "any_": [
                    "testbot-flow"
                ]
            }
        }
    }'''

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL,
        path="/api/flows/filter",
        method="POST",
        body=filter_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(filter_POST_response, "20x")


if __name__ == "__main__":
    test_filter_post()
