# Generated by Skyramp v1.3.12 on 2026-03-13 14:09:38.388126377 +0000 UTC m=+156.107702529
# Command: skyramp generate contract rest http://localhost:4200/api/flows/00000000-0000-0000-0000-000000000001 \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_get_version_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id} GET
def test_endpoint_00000000_0000_0000_0000_000000000001_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create a flow to obtain a real ID for chaining
    setup_POST_request_body = r'''{"name": "flow-get-version-contract-test", "tags": [], "labels": {}}'''
    setup_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=setup_POST_request_body,
        headers=headers
    )
    assert setup_POST_response.status_code in (200, 201)

    # Expected Response Body
    expected_endpoint_00000000_0000_0000_0000_000000000001_GET_response_body = r'''{
        "created": "string",
        "id": "55d992e8-db3c-4fe5-ac7f-4e2869d3292b",
        "labels": {},
        "name": "my-flow",
        "tags": [
            "string"
        ],
        "updated": "string",
        "version": 1
    }'''

    # Execute Request
    endpoint_00000000_0000_0000_0000_000000000001_GET_response = client.send_request(
        url=URL,
        path="/api/flows/{flow_id}",
        method="GET",
        headers=headers,
        path_params={"flow_id": skyramp.get_response_value(setup_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_00000000_0000_0000_0000_000000000001_GET_response.status_code == 200
    assert skyramp.check_schema(endpoint_00000000_0000_0000_0000_000000000001_GET_response, expected_endpoint_00000000_0000_0000_0000_000000000001_GET_response_body)
    assert skyramp.get_response_value(endpoint_00000000_0000_0000_0000_000000000001_GET_response, "created") is not None
    assert skyramp.get_response_value(endpoint_00000000_0000_0000_0000_000000000001_GET_response, "id") is not None
    assert skyramp.get_response_value(endpoint_00000000_0000_0000_0000_000000000001_GET_response, "labels") is not None


if __name__ == "__main__":
    test_endpoint_00000000_0000_0000_0000_000000000001_get()
