# Generated by Skyramp v1.3.12 on 2026-03-13 19:41:23.046850614 +0000 UTC m=+256.030363607
# Command: skyramp generate contract rest http://localhost:4200/api/task_runs \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_task_run_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"contract-test-task-run","flow_run_id":null,"task_key":"contract_test_task","dynamic_key":"contract-1","tags":["contract-test"]} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task_runs POST
def test_task_runs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    task_runs_POST_request_body = r'''{
        "dynamic_key": "contract-1",
        "flow_run_id": null,
        "name": "contract-test-task-run",
        "tags": [
            "contract-test"
        ],
        "task_key": "contract_test_task"
    }'''

    # Expected Response Body — validates new mapped/map_index fields from PR
    expected_task_runs_POST_response_body = r'''{
        "created": "string",
        "dynamic_key": "string",
        "empirical_policy": {
            "max_retries": 0,
            "retry_delay_seconds": 0
        },
        "estimated_run_time": 0,
        "estimated_start_time_delta": 0,
        "expected_start_time": "string",
        "flow_run_run_count": 0,
        "id": "string",
        "labels": {},
        "map_index": -1,
        "mapped": false,
        "name": "string",
        "run_count": 0,
        "state_name": "string",
        "state_type": "string",
        "tags": [],
        "task_inputs": {},
        "task_key": "string",
        "total_run_time": 0,
        "updated": "string"
    }'''

    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL,
        path="/api/task_runs/",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert task_runs_POST_response.status_code in (200, 201)
    # Validate PR-added fields: mapped (bool) and map_index (int) are present in response
    assert skyramp.get_response_value(task_runs_POST_response, "mapped") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "map_index") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "id") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "task_key") is not None
    assert skyramp.get_response_value(task_runs_POST_response, "created") is not None


if __name__ == "__main__":
    test_task_runs_post()
