# Generated by Skyramp v1.3.12 on 2026-03-13 19:41:23.328801823 +0000 UTC m=+256.312314816
# Command: skyramp generate fuzz rest http://localhost:4200/api/task_runs \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_task_run_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"fuzz-test-task-run","flow_run_id":null,"task_key":"fuzz_test_task","dynamic_key":"fuzz-1","tags":[]} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/task_runs POST
def test_task_runs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    task_runs_POST_request_body = r'''{
      "name": "fuzz-test-task-run",
      "flow_run_id": null,
      "task_key": "fuzz_test_task",
      "dynamic_key": "fuzz-1",
      "tags": []
    }'''
    
    # Fuzz strategies
    task_runs_post_fuzzed_body = {
        "dynamic_key": "0123456789",
        "flow_run_id": "\u003cnil\u003e",
        "name": "0123456789",
        "tags": [],
        "task_key": "0123456789"
    }
    # Fuzz status codes
    expected_task_runs_post_status_code = {
        "dynamic_key": "40x",
        "flow_run_id": "40x",
        "name": "40x",
        "tags": [],
        "task_key": "40x"
    }
    # Fuzz status codes for Null values
    expected_task_runs_post_null_status_code = {
        "dynamic_key": "40x",
        "flow_run_id": "40x",
        "name": "40x",
        "tags": [],
        "task_key": "40x"
    }

    # Execute Request
    task_runs_POST_response = client.send_request(
        url=URL,
        path="/api/task_runs/",
        method="POST",
        body=task_runs_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(task_runs_post_fuzzed_body):
        # Execute Request
        task_runs_POST_response = client.send_request(
            url=URL,
            path="/api/task_runs/",
            method="POST",
            body=task_runs_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(task_runs_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_task_runs_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(task_runs_post_fuzzed_body, key) }'
        )

        # Execute Request
        task_runs_POST_response = client.send_request(
            url=URL,
            path="/api/task_runs/",
            method="POST",
            body=task_runs_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_task_runs_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_task_runs_post()
