# Generated by Skyramp v1.3.13 on 2026-03-17 02:46:20.310899322 +0000 UTC m=+123.680418220
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_deployment_schedule_preview_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_deployment-schedule-preview.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "schedule-preview-test-flow-20240101"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    import json as _json
    endpoint_1_POST_request_body = _json.dumps({
        "flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id"),
        "name": "schedule-preview-deploy",
        "schedules": [
            {
                "active": True,
                "schedule": {
                    "cron": "0 * * * *",
                    "timezone": "UTC"
                }
            }
        ]
    })

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    preview_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/deployments/{deployments}/schedules/preview",
        method="GET",
        headers=headers,
        path_params={"deployments": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert preview_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
