# Generated by Skyramp v1.3.12 on 2026-03-12 21:00:24.990795129 +0000 UTC m=+198.938937624
# Command: skyramp generate fuzz rest http://127.0.0.1:4200/api/flows/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_version_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"flow-fuzz-test","version":1,"tags":[],"labels":{}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# fuzz test for /api/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
      "name": "flow-fuzz-test",
      "version": 1,
      "tags": [],
      "labels": {}
    }'''
    
    # Fuzz strategies
    flows_post_fuzzed_body = {
        "labels": {},
        "name": "0123456789",
        "tags": [],
        "version": -10
    }
    # Fuzz status codes
    expected_flows_post_status_code = {
        "labels": "40x",
        "name": "40x",
        "tags": [],
        "version": "40x"
    }
    # Fuzz status codes for Null values
    expected_flows_post_null_status_code = {
        "labels": "40x",
        "name": "40x",
        "tags": [],
        "version": "40x"
    }

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(flows_post_fuzzed_body):
        # Execute Request
        flows_POST_response = client.send_request(
            url=URL,
            path="/api/flows/",
            method="POST",
            body=flows_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(flows_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_flows_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(flows_post_fuzzed_body, key) }'
        )

        # Execute Request
        flows_POST_response = client.send_request(
            url=URL,
            path="/api/flows/",
            method="POST",
            body=flows_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_flows_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_flows_post()
