# Generated by Skyramp v1.3.12 on 2026-03-12 17:18:42.377842844 +0000 UTC m=+149.197504397
# Command: skyramp generate contract rest http://localhost:4200/api/flows/00000000-0000-0000-0000-000000000001 \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_flow_update_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"tags":["contract-test"],"labels":{"env":"test","owner":"testbot"}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/00000000-0000-0000-0000-000000000001 PATCH
def test_endpoint_00000000_0000_0000_0000_000000000001_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body = r'''{
        "labels": {
            "env": "test",
            "owner": "testbot"
        },
        "tags": [
            "contract-test"
        ]
    }'''

    # Execute Request
    endpoint_00000000_0000_0000_0000_000000000001_PATCH_response = client.send_request(
        url=URL,
        path="/api/flows/00000000-0000-0000-0000-000000000001",
        method="PATCH",
        body=endpoint_00000000_0000_0000_0000_000000000001_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_00000000_0000_0000_0000_000000000001_PATCH_response, "20x")


if __name__ == "__main__":
    test_endpoint_00000000_0000_0000_0000_000000000001_patch()
