# Generated by Skyramp v1.3.12 on 2026-03-12 19:16:00.641269442 +0000 UTC m=+178.323290976
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_create_filter_delete.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/skyramp-tests/scenario_flow-create-filter-delete.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {
            "env": "staging",
            "team": "backend"
        },
        "name": "filter-test-flow-20260312",
        "tags": [
            "testbot",
            "filter-test"
        ],
        "version": 2
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    filter_POST_request_body = r'''{
        "flows": {
            "name": {
                "any_": [
                    "filter-test-flow-20260312"
                ]
            }
        }
    }'''
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 200

    # Execute Request
    flows_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="DELETE",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
