# Generated by Skyramp v1.3.19 on 2026-04-20 14:44:34.337171215 +0000 UTC m=+394.833874319
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/bulk_cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output bulk_cancel_200_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_ids":[],"reason":"Contract test cancellation"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/bulk_cancel POST
def test_bulk_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bulk_cancel_POST_request_body = r'''{
        "flow_run_ids": [],
        "reason": "Contract test cancellation"
    }'''

    # Execute Request
    bulk_cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/bulk_cancel",
        method="POST",
        body=bulk_cancel_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bulk_cancel_POST_response.status_code == 200


if __name__ == "__main__":
    test_bulk_cancel_post()
