# Generated by Skyramp v1.3.19 on 2026-04-20 14:44:59.770012778 +0000 UTC m=+420.266715892
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output bulk_cancel_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_bulk_cancel_post_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    flows_POST_request_body = r'''{
        "name": "test-flow-1745193600"
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201

    flow_id = skyramp.get_response_value(flows_POST_response, "id")
    # Request Body
    flow_runs_POST_request_body = '{"flow_id": "' + str(flow_id) + '", "name": "test-flow-run-1745193600"}'
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs",
        method="POST",
        body=flow_runs_POST_request_body
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201

    flow_run_id = skyramp.get_response_value(flow_runs_POST_response, "id")
    # Request Body
    bulk_cancel_POST_request_body = '{"flow_run_ids": ["' + str(flow_run_id) + '"], "reason": "Integration test cancellation"}'
    
    # Execute Request
    bulk_cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/bulk_cancel",
        method="POST",
        body=bulk_cancel_POST_request_body
    )
    # Generated Assertions
    assert bulk_cancel_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
