# Generated by Skyramp v1.3.19 on 2026-04-21 17:39:18.343573427 +0000 UTC m=+247.419411365
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output cancel_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cancel_post_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    cancel_POST_request_body = r'''{}'''
    
    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/c7f8a9b0-d1e2-4f35-96a7-b8c9d0e1f2a3/cancel",
        method="POST",
        body=cancel_POST_request_body
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 201


if __name__ == "__main__":
    test_integration()
