# Generated by Skyramp v1.3.19 on 2026-04-21 17:32:51.249314755 +0000 UTC m=+388.842183892
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output cron_5field_schedule_workflow_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cron_5field_schedule_workflow.json

# Import of required libraries
import skyramp
import json
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "cron-schedule-flow-1745200000"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "cron-schedule-flow-1745200000"

    # Request Body
    endpoint_1_POST_request_body = json.dumps({
        "name": "cron-schedule-deploy-1745200000",
        "flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id"),
        "schedules": [
            {
                "active": True,
                "schedule": {
                    "cron": "0 9 * * 1-5",
                    "timezone": "UTC"
                }
            }
        ]
    })

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "cron-schedule-deploy-1745200000"

    # Execute Request
    schedules_GET_response = client.send_request(
        url=URL_,
        path="/api/deployments/{deployments}/schedules",
        method="GET",
        path_params={"deployments": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert schedules_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
