# Generated by Skyramp v1.3.19 on 2026-04-20 13:18:59.537606588 +0000 UTC m=+280.536887723
# Command: skyramp generate contract rest http://localhost:4200/api/deployments/{id} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=7d4e9f2a-1b3c-4d5e-8f6a-9b7c8d9e0f1a \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/deployments/{id} DELETE
def test_deployments_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "7d4e9f2a-1b3c-4d5e-8f6a-9b7c8d9e0f1a"

    # Execute Request
    deployments_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/deployments/{id}",
        method="DELETE",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(deployments_id_DELETE_response, "404")


if __name__ == "__main__":
    test_deployments_id_delete()
