# Generated by Skyramp v1.3.19 on 2026-04-20 13:03:46.013848031 +0000 UTC m=+346.444703820
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output deployment_max_active_runs_validation_boundary_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_deployment_max_active_runs_validation_boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-1745000001"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{"flow_id": "' + str(skyramp.get_response_value(endpoint_2_POST_response, "id")) + '", "name": "test-deploy-1745000001"}'

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    deployments = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    create_flow_run_POST_request_body = r'''{
        "flow_run": {},
        "max_active_runs": 0
    }'''
    
    # Execute Request
    create_flow_run_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/{deployments}/create_flow_run",
        method="POST",
        body=create_flow_run_POST_request_body,
        headers=headers,
        path_params={"deployments": deployments}
    )
    # Generated Assertions
    assert create_flow_run_POST_response.status_code == 422


if __name__ == "__main__":
    test_integration()
