# Generated by Skyramp v1.3.19 on 2026-04-21 15:30:41.52679563 +0000 UTC m=+233.270061762
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_create_verify_recent_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_create_verify_recent.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "name": "skyramp-test-flow-1713600000"
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") == "skyramp-test-flow-1713600000"

    # Execute Request
    recent_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/recent",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert recent_GET_response.status_code == 200
    assert skyramp.get_response_value(recent_GET_response, "0.id") is not None
    assert skyramp.get_response_value(recent_GET_response, "0.name") is not None
    assert skyramp.get_response_value(recent_GET_response, "0.id") == skyramp.get_response_value(flows_POST_response, "id")


if __name__ == "__main__":
    test_integration()
