# Generated by Skyramp v1.3.19 on 2026-04-20 13:38:48.8084362 +0000 UTC m=+380.357291801
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id}/star \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output flows_star_delete_404_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=b9f8e7d6-c5b4-a392-8170-fedcba987654 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id}/star DELETE
def test_star_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "b9f8e7d6-c5b4-a392-8170-fedcba987654"

    # Execute Request
    star_DELETE_response = client.send_request(
        url=URL,
        path="/api/flows/{id}/star",
        method="DELETE",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert star_DELETE_response.status_code == 404


if __name__ == "__main__":
    test_star_delete()
