# Generated by Skyramp v1.3.19 on 2026-04-20 13:18:54.937240814 +0000 UTC m=+275.936521939
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_delete_admin_key_backward_compat_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_delete_admin_key_backward_compat.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    flows_POST_request_body = r'''{
        "name": "test-flow-1745191284"
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") == "test-flow-1745191284"

    # Execute Request
    flows_flows_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="DELETE",
        path_params={"flows": skyramp.get_response_value(flows_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_flows_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
