# Generated by Skyramp v1.3.23 on 2026-05-11 19:08:30.357493905 +0000 UTC m=+426.578778136
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flows_create_with_description_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flows-create-with-description.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Use timestamp to ensure unique flow name across test runs
    flow_name = f"etl-flow-{int(time.time())}"

    # Request Body
    endpoint_1_POST_request_body = f'''{{
        "description": "Daily ETL for analytics",
        "name": "{flow_name}"
    }}'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == flow_name
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "Daily ETL for analytics"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(endpoint_1_POST_response, "id"), re.I)
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', skyramp.get_response_value(endpoint_1_POST_response, "created"))
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', skyramp.get_response_value(endpoint_1_POST_response, "updated"))

    # Execute Request
    flows_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="GET",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_GET_response.status_code == 200
    assert skyramp.get_response_value(flows_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(flows_GET_response, "name") == flow_name
    assert skyramp.get_response_value(flows_GET_response, "description") == "Daily ETL for analytics"

    # Execute Request
    flows_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="DELETE",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flows_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
