# Generated by Skyramp v1.3.23 on 2026-05-11 19:07:52.314085847 +0000 UTC m=+388.535370099
# Command: skyramp generate contract rest http://localhost:4200/api/flows/ \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flows_POST_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"etl-flow-test","description":"Daily ETL for analytics"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "description": "Daily ETL for analytics",
        "name": "etl-flow-test"
    }'''

    # Expected Response Body
    expected_flows_POST_response_body = r'''{
        "created": "2026-05-11T19:07:52Z",
        "description": "Daily ETL for analytics",
        "id": "29bf1a26-c3f5-48d3-baea-c5db42c711ae",
        "name": "etl-flow-test",
        "updated": "2026-05-11T19:07:52Z"
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.check_schema(flows_POST_response, expected_flows_POST_response_body)
    assert skyramp.get_response_value(flows_POST_response, "created") is not None
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") == "etl-flow-test"
    assert skyramp.get_response_value(flows_POST_response, "description") == "Daily ETL for analytics"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(flows_POST_response, "id"), re.I)
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', skyramp.get_response_value(flows_POST_response, "created"))
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', skyramp.get_response_value(flows_POST_response, "updated"))


if __name__ == "__main__":
    test_flows_post()
