# Generated by Skyramp v1.3.19 on 2026-04-18 00:23:53.130056161 +0000 UTC m=+300.082569222
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_runs_page_size_boundary_validation_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_runs_page_size_boundary_validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    filter_POST_request_body = r'''{
        "page": 1,
        "page_size": 201
    }'''
    
    # Request Body
    filter_POST_1_request_body = r'''{
        "page": 0
    }'''
    
    # Request Body
    filter_POST_2_request_body = r'''{
        "page": 1,
        "page_size": 200
    }'''
    
    # Request Body
    filter_POST_request_body = r'''{
        "page": 1,
        "page_size": 201
    }'''
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 422

    # Request Body
    filter_POST_1_request_body = r'''{
        "page": 0
    }'''
    
    # Request Body
    filter_POST_2_request_body = r'''{
        "page": 1,
        "page_size": 200
    }'''
    
    # Request Body
    filter_POST_1_request_body = r'''{
        "page": 0
    }'''
    
    # Execute Request
    filter_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/filter",
        method="POST",
        body=filter_POST_1_request_body
    )
    # Generated Assertions
    assert filter_POST_1_response.status_code == 422

    # Request Body
    filter_POST_2_request_body = r'''{
        "page": 1,
        "page_size": 200
    }'''
    
    # Request Body
    filter_POST_2_request_body = r'''{
        "page": 1,
        "page_size": 200
    }'''
    
    # Execute Request
    filter_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/filter",
        method="POST",
        body=filter_POST_2_request_body
    )
    # Generated Assertions
    assert filter_POST_2_response.status_code == 200


if __name__ == "__main__":
    test_integration()
