# Generated by Skyramp v1.3.19 on 2026-04-21 17:46:14.365661039 +0000 UTC m=+193.340596069
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_create_get_run_legacy_404_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_create_get_run_legacy_404.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "test-flow-legacy-retire"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "test-flow-legacy-retire"

    flows = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    flows_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}",
        method="GET",
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert flows_GET_response.status_code == 200
    assert skyramp.get_response_value(flows_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(flows_GET_response, "name") == "test-flow-legacy-retire"

    # Request Body
    run_legacy_POST_request_body = r'''{}'''
    
    # Execute Request
    run_legacy_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}/run-legacy",
        method="POST",
        body=run_legacy_POST_request_body,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert run_legacy_POST_response.status_code == 404


if __name__ == "__main__":
    test_integration()
