# Generated by Skyramp v1.3.19 on 2026-04-18 00:23:51.575773654 +0000 UTC m=+298.528286705
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_runs_page_pagination_offset_bug_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_runs_page_pagination_offset_bug.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    flows_POST_request_body = r'''{
        "name": "skyramp-flow-1745129600"
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.get_response_value(flows_POST_response, "id") is not None

    # Request Body
    _flow_id = skyramp.get_response_value(flows_POST_response, "id")
    flow_runs_POST_request_body = '{"flow_id": "' + _flow_id + '", "name": "skyramp-run-1745129600"}'
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=flow_runs_POST_request_body
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201
    assert skyramp.get_response_value(flow_runs_POST_response, "id") is not None
    assert skyramp.get_response_value(flow_runs_POST_response, "flow_id") == skyramp.get_response_value(flows_POST_response, "id")

    # Request Body
    filter_POST_request_body = '{"page": 1, "page_size": 200, "flows": {"id": {"any_": ["' + skyramp.get_response_value(flows_POST_response, "id") + '"]}}}'
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 200
    assert skyramp.get_response_value(filter_POST_response, "0.id") == skyramp.get_response_value(flow_runs_POST_response, "id")


if __name__ == "__main__":
    test_integration()
