# Generated by Skyramp v1.3.19 on 2026-04-18 00:23:54.988365836 +0000 UTC m=+301.940878897
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/filter \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_runs_filter_page_pagination_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"page":1,"page_size":20} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/filter POST
def test_filter_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    filter_POST_request_body = r'''{
        "page": 1,
        "page_size": 20
    }'''

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/filter",
        method="POST",
        body=filter_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(filter_POST_response, "20x")


if __name__ == "__main__":
    test_filter_post()
