# Generated by Skyramp v1.3.19 on 2026-04-21 17:46:02.972004279 +0000 UTC m=+181.946939299
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id}/run-legacy \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flows_run_legacy_POST_404_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=a7b8c9d0-e1f2-3456-7890-abcdef012345 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id}/run-legacy POST
def test_run_legacy_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a7b8c9d0-e1f2-3456-7890-abcdef012345"

    # Execute Request
    run_legacy_POST_response = client.send_request(
        url=URL,
        path="/api/flows/{id}/run-legacy",
        method="POST",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert run_legacy_POST_response.status_code == 404


if __name__ == "__main__":
    test_run_legacy_post()
