# Generated by Skyramp v1.3.19 on 2026-04-21 17:38:38.31081616 +0000 UTC m=+207.386654098
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/cancel \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_runs_cancel_POST_422_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=c7f8a9b0-d1e2-4f35-96a7-b8c9d0e1f2a3 \
# 		--provider \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "c7f8a9b0-d1e2-4f35-96a7-b8c9d0e1f2a3"

    # Expected Response Body
    expected_cancel_POST_response_body = r'''{
        "detail": [
            {
                "loc": [
                    "path"
                ],
                "msg": "Field required",
                "type": "missing"
            }
        ]
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/cancel",
        method="POST",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert cancel_POST_response.status_code == 422
    assert skyramp.check_schema(cancel_POST_response, expected_cancel_POST_response_body)
    assert skyramp.get_response_value(cancel_POST_response, "detail.0.loc.0") is not None
    assert skyramp.get_response_value(cancel_POST_response, "detail.0.msg") is not None
    assert skyramp.get_response_value(cancel_POST_response, "detail.0.type") is not None


if __name__ == "__main__":
    test_cancel_post()
