# Generated by Skyramp v1.3.19 on 2026-04-20 13:19:13.650992282 +0000 UTC m=+294.650273428
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id} DELETE
def test_flows_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Execute Request
    flows_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/flows/{id}",
        method="DELETE",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(flows_id_DELETE_response, "404")


if __name__ == "__main__":
    test_flows_id_delete()
