# Generated by Skyramp v1.3.19 on 2026-04-21 17:22:34.075768583 +0000 UTC m=+362.366834025
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output flow_cost_profile_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_cost_profile_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "a2b3c4d5-e6f7-8901-bcde-f12345678901"

    # Request Body
    endpoint_2_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-profile/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_POST_response, "flow_id") == flows
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "currency") == "USD"
    assert skyramp.get_response_value(endpoint_2_POST_response, "cost_per_second") >= 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "cost_per_task") >= 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "fixed_cost_per_run") >= 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-profile/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "flow_id") == skyramp.get_response_value(endpoint_2_POST_response, "flow_id")
    assert skyramp.get_response_value(endpoint_2_GET_response, "cost_profile.id") is not None
    assert skyramp.get_response_value(endpoint_2_GET_response, "cost_profile.currency") == "USD"
    assert skyramp.get_response_value(endpoint_2_GET_response, "current_spending.total_cost") >= 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "current_spending.total_runs") >= 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-history/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "flow_id") == skyramp.get_response_value(endpoint_2_POST_response, "flow_id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "period_days") == 30
    assert skyramp.get_response_value(endpoint_1_GET_response, "total_runs") >= 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "total_cost") >= 0


if __name__ == "__main__":
    test_integration()
