# Generated by Skyramp v1.3.19 on 2026-04-20 13:37:08.170760425 +0000 UTC m=+279.719616036
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id}/star \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flows_star_422_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=not-a-valid-uuid-format-xyz \
# 		--provider \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id}/star POST
def test_star_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "not-a-valid-uuid-format-xyz"

    # Execute Request
    star_POST_response = client.send_request(
        url=URL,
        path="/api/flows/{id}/star",
        method="POST",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert star_POST_response.status_code == 422


if __name__ == "__main__":
    test_star_post()
