# Generated by Skyramp v1.3.19 on 2026-04-21 17:46:19.785794593 +0000 UTC m=+198.760729621
# Command: skyramp generate contract rest http://localhost:4200/api/flows/{id} \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output flows_id_GET_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--parent-request-data id={"name": "test-flow-get-contract"} \
# 		--parent-status-code id=200 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/{id} GET
def test_flows_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "6eadd9a5-c0d9-4596-98d2-402d24ef0257"

    # Expected Response Body
    expected_flows_id_GET_response_body = r'''{
        "created": "string",
        "id": "34c2056c-b638-4df0-a8a2-082309960177",
        "name": "my-flow",
        "updated": "string"
    }'''

    # Execute Request
    flows_id_GET_response = client.send_request(
        url=URL,
        path="/api/flows/{id}",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert flows_id_GET_response.status_code == 200
    assert skyramp.check_schema(flows_id_GET_response, expected_flows_id_GET_response_body)
    assert skyramp.get_response_value(flows_id_GET_response, "created") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "id") is not None
    assert skyramp.get_response_value(flows_id_GET_response, "name") is not None


if __name__ == "__main__":
    test_flows_id_get()
