# Generated by Skyramp v1.3.19 on 2026-04-21 17:22:22.236966597 +0000 UTC m=+350.528032039
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/flows/{flow_id}/cost-profile/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d \
# 		--provider \
# 		--response-data {"id":"cp-d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d","flow_id":"d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d","currency":"USD","cost_per_second":0.0001,"cost_per_task":0.05,"cost_per_gb_memory":0.0025,"fixed_cost_per_run":0.10,"created_at":"2024-01-01T00:00:00","updated_at":"2024-01-01T00:00:00"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/flows/{flow_id}/cost-profile/ POST
def test_cost_profile_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d"

    # Expected Response Body
    expected_cost_profile_POST_response_body = r'''{
        "cost_per_gb_memory": 0.0025,
        "cost_per_second": 0.0001,
        "cost_per_task": 0.05,
        "created_at": "2024-01-01T00:00:00",
        "currency": "USD",
        "fixed_cost_per_run": 0.1,
        "flow_id": "d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d",
        "id": "cp-d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d",
        "updated_at": "2024-01-01T00:00:00"
    }'''

    # Execute Request
    cost_profile_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/flows/{flow_id}/cost-profile/",
        method="POST",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(cost_profile_POST_response, "20x")
    assert skyramp.check_schema(cost_profile_POST_response, expected_cost_profile_POST_response_body)
    assert skyramp.get_response_value(cost_profile_POST_response, "cost_per_gb_memory") is not None
    assert skyramp.get_response_value(cost_profile_POST_response, "cost_per_second") is not None
    assert skyramp.get_response_value(cost_profile_POST_response, "cost_per_task") is not None
    assert skyramp.get_response_value(cost_profile_POST_response, "flow_id") == "d4e8f1a3-7c25-4b9e-83d2-1b4c6e8f0a2d"
    assert skyramp.get_response_value(cost_profile_POST_response, "id") is not None
    assert skyramp.get_response_value(cost_profile_POST_response, "currency") == "USD"
    assert skyramp.get_response_value(cost_profile_POST_response, "cost_per_second") == 0.0001
    assert skyramp.get_response_value(cost_profile_POST_response, "cost_per_task") == 0.05
    assert skyramp.get_response_value(cost_profile_POST_response, "fixed_cost_per_run") == 0.1


if __name__ == "__main__":
    test_cost_profile_post()
