# Generated by Skyramp v1.3.19 on 2026-04-21 15:30:13.174796698 +0000 UTC m=+204.918062830
# Command: skyramp generate contract rest http://localhost:4200/api/flows/recent \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recent_flows_GET_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/recent GET
def test_recent_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    recent_GET_response = client.send_request(
        url=URL,
        path="/api/flows/recent",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert recent_GET_response.status_code == 200
    assert skyramp.get_response_value(recent_GET_response, "0.id") is not None
    assert skyramp.get_response_value(recent_GET_response, "0.name") is not None


if __name__ == "__main__":
    test_recent_get()
