# Generated by Skyramp v1.3.19 on 2026-04-21 15:30:16.755113219 +0000 UTC m=+208.498379351
# Command: skyramp generate contract rest http://localhost:4200/api/flows/recent \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recent_flows_GET_consumer_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/recent GET
def test_recent_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flows/recent",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    recent_GET_response = client.send_request(
        url=URL,
        path="/api/flows/recent",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert recent_GET_response.status_code == 200

    client.remove_all_mocks()


if __name__ == "__main__":
    test_recent_get()
