# Generated by Skyramp v1.3.19 on 2026-04-20 13:37:18.743292116 +0000 UTC m=+290.292147717
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output star_delete_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_star_delete_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "star-flow-test-1700000000"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "star-flow-test-1700000000"

    # Chain flow id from create response
    flows = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    star_POST_request_body = r'''{}'''

    # Execute Request
    star_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}/star",
        method="POST",
        body=star_POST_request_body,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert star_POST_response.status_code == 200
    assert skyramp.get_response_value(star_POST_response, "id") is not None
    assert skyramp.get_response_value(star_POST_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(star_POST_response, "name") == "star-flow-test-1700000000"
    assert skyramp.get_response_value(star_POST_response, "labels.starred") == True

    # Execute Request
    star_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/{flows}/star",
        method="DELETE",
        path_params={"flows": skyramp.get_response_value(star_POST_response, "id")}
    )
    # Generated Assertions
    assert star_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
