# Generated by Skyramp v1.3.19 on 2026-04-21 22:11:24.016930865 +0000 UTC m=+391.789344131
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/work_queues/{id}/stats \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output stats_GET_404_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=c9ba1b7e-a012-4e9f-bc93-21c15a07b842 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/work_queues/{id}/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "c9ba1b7e-a012-4e9f-bc93-21c15a07b842"

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}/stats",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert stats_GET_response.status_code == 404


if __name__ == "__main__":
    test_stats_get()
