# Generated by Skyramp v1.3.19 on 2026-04-21 22:10:44.651154884 +0000 UTC m=+352.423568148
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/work_queues/{id}/stats \
# 		--api-schema http://127.0.0.1:4200/api/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--parent-request-data id={"name": "TestQueue-1745286000"} \
# 		--parent-status-code id=201 \
# 		--provider \
# 		--response-data {"running":0,"pending":0,"scheduled_count":0} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/work_queues/{id}/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Create parent work queue to provision the resource under test
    create_response = client.send_request(
        url=URL,
        path="/api/work_queues/",
        method="POST",
        body='{"name": "TestQueue-' + str(int(time.time())) + '"}',
        headers=headers
    )
    assert create_response.status_code == 201
    id = skyramp.get_response_value(create_response, "id")

    # Expected Response Body
    expected_stats_GET_response_body = r'''{
        "pending": 0,
        "running": 0,
        "scheduled_count": 0
    }'''

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}/stats",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.check_schema(stats_GET_response, expected_stats_GET_response_body)
    assert skyramp.get_response_value(stats_GET_response, "pending") is not None
    assert skyramp.get_response_value(stats_GET_response, "running") is not None
    assert skyramp.get_response_value(stats_GET_response, "scheduled_count") is not None
    assert skyramp.get_response_value(stats_GET_response, "running") >= 0
    assert skyramp.get_response_value(stats_GET_response, "pending") >= 0
    assert skyramp.get_response_value(stats_GET_response, "scheduled_count") >= 0


if __name__ == "__main__":
    test_stats_get()
