# Generated by Skyramp v1.3.12 on 2026-03-12 17:04:32.119698653 +0000 UTC m=+149.429558222
# Command: skyramp generate contract rest http://localhost:4200/api/flows/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_create_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"contract-test-flow-20260312","tags":[],"labels":{},"version":1} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "labels": {},
        "name": "contract-test-flow-20260312",
        "tags": [],
        "version": 1
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flows_POST_response, "20x")


if __name__ == "__main__":
    test_flows_post()
