# Generated by Skyramp v1.3.19 on 2026-04-21 22:10:59.352992564 +0000 UTC m=+367.125405826
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_stats_workflow_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work_queue_stats_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "TestQueue-1745286000"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestQueue-1745286000"

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_,
        path="/api/work_queues/{work_queues}/stats",
        method="GET",
        headers=headers,
        path_params={"work_queues": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.get_response_value(stats_GET_response, "running") is not None
    assert skyramp.get_response_value(stats_GET_response, "running") >= 0
    assert skyramp.get_response_value(stats_GET_response, "pending") is not None
    assert skyramp.get_response_value(stats_GET_response, "pending") >= 0
    assert skyramp.get_response_value(stats_GET_response, "scheduled_count") is not None
    assert skyramp.get_response_value(stats_GET_response, "scheduled_count") >= 0


if __name__ == "__main__":
    test_integration()
